### ISSUE TITLE
May I create a GUI client?

### ISSUE THREAD

**Issue by piotrkubisa** [nathan-alden/windows-10-tracking#2]
I greatly appreciate your work, fabulous job @nathan-alden! The new terminal in windows10 is also awesome, but I think there are some drawbacks in using it connected with such useful application (oh yeah, I do not imagine live without CLI), I think it will be nice to create a simple, eye-catching GUI based on WPF/Universal Windows framework (C#). I have some experience in developing C# apps and I'd like to help you promote this project instead of erm.. _the root_, which is... well, _bad managed_.

**Comment by ocdtrekkie** [comment]
+1 for this. IMHO, good robust tools should have two things: A simple GUI and a robust CLI.

**Comment by nathan-alden-sr** [comment]
Are you asking to contribute to this repository? If so, then I have only one request: the actual logic that does the work must be in a single place (DRY). I'd prefer if the PowerShell script retains the logic with the GUI simply making calls to the script. Do you think that's doable?

Also, I don't have any experience managing builds or releases through GitHub; I usually use repositories just for code. I expect you'd want to host the releases in the repository. If you know how, then that's great. :)

**Comment by piotrkubisa** [comment]
Sure it is able to do, but unfortunately the logic of powershell will be needed to be divided into small parts - just like additional parameters passed inline during cmd session. During my .psl file investigation I must admit that is almost done. You can pass parameter to only disable or delete or even enable tracking features. So yes - consider it done... 

PS. When I only bootstrap application and install VM with Win10 to test it I will push the very first version to https://github.com/piqus/windows10-tweak.

**Comment by nathan-alden-sr** [comment]
Thanks for your interest, piqus. :+1: I added you as a collaborator. Also, please take a look at the new README and folder structure. I made some significant changes to their organization to better allow you to get started.

So you're aware, I'm pretty busy working on a very important project so I won't be able to contribute much more than I already have. I'll check in from time to time, though. Good luck!

**Comment by piotrkubisa** [comment]
Yay! I really appreciate that, thank you! I am goting to get into developing things asap.
