### ISSUE TITLE
Question about tracking

### ISSUE THREAD

**Issue by romu70** [nathan-alden/windows-10-tracking#3]
Hi Nathan,
Thanks a lot for the scripts, that's really helpful. Why do you write "not intended to remove all tracking"? Is there any really useful tracking?

Could be nice to give the user the choice to really more if it's possible and easy to implement.

**Comment by nathan-alden-sr** [comment]
I wrote that because there are probably many as-yet unfound tracking methods still embedded in Windows 10. I wanted to make it clear that the script doesn't claim to eliminate _all_ tracking.
